openapi: 3.0.3
info:
  title: Transaction API
  version: 1.0.0
paths:
  /transaction/create:
    post:
      summary: Create a new transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateTransactionRequest"
      responses:
        "200":
          description: Transaction created
          content:
            application/json:
              schema:
                type: object
        "500":
          description: Internal server error

  /transaction/{transactionId}/charge:
    post:
      summary: Charge a transaction
      parameters:
        - name: transactionId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Transaction charged
          content:
            application/json:
              schema:
                type: object
        "404":
          description: Not found
        "400":
          description: Missing or malformed transactionId
        "500":
          description: Internal server error

  /transaction/{transactionId}/charge-fees:
    post:
      summary: Charge transaction fees
      parameters:
        - name: transactionId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Fees charged
          content:
            application/json:
              schema:
                type: object
        "404":
          description: Not found
        "400":
          description: Missing or malformed transactionId
        "500":
          description: Internal server error

  /transaction/{transactionId}:
    get:
      summary: Get a transaction by ID
      parameters:
        - name: transactionId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Transaction details
          content:
            application/json:
              schema:
                type: object
        "404":
          description: Not found
        "400":
          description: Missing or malformed transactionId
        "500":
          description: Internal server error

  /transaction/{transactionId}/applicable-fees:
    get:
      summary: Get applicable fees for a transaction
      parameters:
        - name: transactionId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Applicable fees
          content:
            application/json:
              schema:
                type: object
        "404":
          description: Not found
        "400":
          description: Missing or malformed transactionId
        "500":
          description: Internal server error

components:
  schemas:
    CreateTransactionRequest:
      type: object
      properties:
        amount:
          type: number
          format: double
        asset:
          $ref: "#/components/schemas/Asset"
        assetType:
          $ref: "#/components/schemas/AssetType"
        type:
          $ref: "#/components/schemas/TransactionType"
      required:
        - amount
        - asset
        - assetType
        - type
    Asset:
      type: string
      enum:
        - AED
        - USD
        - EUR
        - PHP
        - BTC
        - ETH
    AssetType:
      type: string
      enum:
        - FIAT
        - CRYPTO
    TransactionType:
      type: string
      enum:
        - MOBILE_TOPUP
        - DEPOSIT
        - WITHDRAWAL
        - TRANSFER
        - PAYMENT
        - REFUND
