services:
  web:
    build: .
    environment:
      DATABASE_URL: "jdbc:postgresql://db:5432/ctc"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ktor_tutorial_db
      POSTGRES_HOST_AUTH_METHOD: trust # for this exercise only
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s




         